-- ============================================================================
-- DEPRECATED — DO NOT APPLY.
-- ----------------------------------------------------------------------------
-- This file was a partial schema (notifications table + notification triggers
-- only). It has been fully superseded by the authoritative, ordered migrations
-- under supabase/migrations/ which now define the complete contract:
--
--   20260620000001_core_schema.sql       profiles / matches / messages / notifications
--   20260620000002_security_helpers.sql  SECURITY DEFINER RLS helper functions
--   20260620000003_hunter.sql            "The Hunter" trigger + FOR UPDATE SKIP LOCKED
--   20260620000004_notifications.sql      match/message notification triggers (BRD text)
--   20260620000005_rls.sql               RLS policies + column-level privileges
--
-- Validate locally with:  ./supabase/tests/run_local_db_tests.sh
-- ============================================================================
